SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
GO

BEGIN TRY
BEGIN TRANSACTION
UPDATE dbo.Student
SET StudentName = 'Samiran' WHERE StudentId=1014
COMMIT TRANSACTION

END TRY
BEGIN CATCH
SELECT 'Rollback'
ROLLBACK TRANSACTION;
END CATCH

/*(1 row affected)

Completion time: 2020-11-05T19:07:07.9257692+05:30
*/