SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
GO

BEGIN TRY
BEGIN TRANSACTION
UPDATE dbo.Student
SET StudentName = 'Samiran' WHERE StudentId=1014
COMMIT TRANSACTION
END TRY
BEGIN CATCH
	SELECT 'Rollback'
	ROLLBACK TRANSACTION;
END CATCH